# Generated by Django 4.2.8 on 2023-12-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq', models.IntegerField()),
                ('wieght', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='john', max_length=50)),
                ('sex', models.CharField(choices=[('male', 'мужской'), ('female', 'женский'), ('think', 'неопределенный'), ('fight helicopter', 'боевой вертолетик')], max_length=20)),
                ('brain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human', to='OnetoOneApp.brain')),
            ],
        ),
    ]
